name: Build and test app

on: [pull_request, workflow_call]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]  # Use LTS ubuntu due to bug in actions/setup-python@v4 with cache
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install oak for build
        run: |
          poetry install
      - name: Run tests
        run: |
          poetry run oak tests
      - name: Check style
        run: |
          poetry run oak check_style
